-- Add created_by and updated_by columns to tables that inherit AuditableEntity
ALTER TABLE countries ADD COLUMN IF NOT EXISTS created_by VARCHAR(150) NULL;
ALTER TABLE countries ADD COLUMN IF NOT EXISTS updated_by VARCHAR(150) NULL;

ALTER TABLE states ADD COLUMN IF NOT EXISTS created_by VARCHAR(150) NULL;
ALTER TABLE states ADD COLUMN IF NOT EXISTS updated_by VARCHAR(150) NULL;

ALTER TABLE cities ADD COLUMN IF NOT EXISTS created_by VARCHAR(150) NULL;
ALTER TABLE cities ADD COLUMN IF NOT EXISTS updated_by VARCHAR(150) NULL;

ALTER TABLE tenants ADD COLUMN IF NOT EXISTS created_by VARCHAR(150) NULL;
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS updated_by VARCHAR(150) NULL;

ALTER TABLE menus ADD COLUMN IF NOT EXISTS created_by VARCHAR(150) NULL;
ALTER TABLE menus ADD COLUMN IF NOT EXISTS updated_by VARCHAR(150) NULL;

ALTER TABLE menu_templates ADD COLUMN IF NOT EXISTS created_by VARCHAR(150) NULL;
ALTER TABLE menu_templates ADD COLUMN IF NOT EXISTS updated_by VARCHAR(150) NULL;

ALTER TABLE user_templates ADD COLUMN IF NOT EXISTS created_by VARCHAR(150) NULL;
ALTER TABLE user_templates ADD COLUMN IF NOT EXISTS updated_by VARCHAR(150) NULL;

ALTER TABLE users ADD COLUMN IF NOT EXISTS created_by VARCHAR(150) NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS updated_by VARCHAR(150) NULL;

ALTER TABLE password_reset_tokens ADD COLUMN IF NOT EXISTS created_by VARCHAR(150) NULL;
ALTER TABLE password_reset_tokens ADD COLUMN IF NOT EXISTS updated_by VARCHAR(150) NULL;
